name: Run PHP checks

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.2', '8.3', '8.4'] 
    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: composer install --dev
    - name: Execute tests
      run: vendor/bin/pest
